### ISSUE TITLE
It is posible to use step/dir interface??? 

### ISSUE THREAD

**Issue by artayasa** [Zzx-J/MasterFOC#3]
Good day sir. 
Iam intetest with your project, it is posible to implement the step/dir interface??? 
And it posible to drive ac servo with 220v?? I want to change the drv. So used a igbt or mosfet and driver like ir2101

**Comment by Zzx-J** [comment]
Hi, 
Thanks for your interest. This algorithm and hardware is specifically designed for PMSM and BLDC, so it might not suitable for step/dir. As for the 220V capability, if you change the gate driver and mosfet and redesign the PCB based on your current requirement, the FOC algortihm should be ok (but u might need to adjust the PID parameters according to your motor).

Additionally, for the step/dir interface, you might want to look for the simpleFOC project: https://docs.simplefoc.com/step_dir_interface

**Comment by artayasa** [comment]
> Hi, Thanks for your interest. This algorithm and hardware is specifically designed for PMSM and BLDC, so it might not suitable for step/dir. As for the 220V capability, if you change the gate driver and mosfet and redesign the PCB based on your current requirement, the FOC algortihm should be ok (but u might need to adjust the PID parameters according to your motor).
> 
> Additionally, for the step/dir interface, you might want to look for the simpleFOC project: https://docs.simplefoc.com/step_dir_interface

Yes sir. 
But how to change the gate driver?? On your project u used drv sir. That come with SPI pin, when i change drv with ir2101 and igbt or mosfet are can handle 220v (example) how about the spi pin sir?? It need to change the code sir???. 

Yess i know the simple foc but simple foc are exsample only not stabile sir. I see odrive. But they used drv also. If posible dont used spi pin on dev and no need to change code i will try odrive. 

And your code can handle sensored with 2000ppr encoder?? To control potition?? So if posible that must can add step/dir interface to control the posision of pmsm motor sir.

**Comment by Zzx-J** [comment]
The gate driver used in this project is DRV8302 not 8301, i.e. without SPI, the gain for current sampling is set through the "GAIN" pin of the chip.

**Comment by artayasa** [comment]
> The gate driver used in this project is DRV8302 not 8301, i.e. without SPI, the gain for current sampling is set through the "GAIN" pin of the chip.

Owhhh okee sir🙏🙏
